version: '3.7'

services:
  back-banck-api:
    build:
      context: ./back-bank-api/
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: back-bank-api
    restart: always
    networks:
      - bank_network
    ports:
      - '8080:8080'
    expose:
      - '8080'


  back-bank-getapi:
    build:
      context: ./back-bank-getapi/
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: back-bank-getapi
    restart: always
    networks:
      - bank_network
    ports:
      - '8081:8080'
    expose:
      - '8080'

volumes:
  bank_tracing_data:
    driver: local
  bank_prometheus_data:
    driver: local
  bank_grafana_data:
    driver: local

networks:
  bank_network:
    driver: bridge
